"""Module 20 - Aurora: a PostgreSQL-compatible Aurora cluster with one writer instance.

AWS docs used while writing this module:
- DatabaseCluster construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseCluster.html
- ClusterInstance construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/ClusterInstance.html
- DatabaseClusterEngine construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseClusterEngine.html
- AuroraPostgresEngineVersion construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/AuroraPostgresEngineVersion.html
- Credentials construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/Credentials.html
- Secret construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_secretsmanager/Secret.html
- SecretValue.secrets_manager: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/SecretValue.html
- Secrets Manager dynamic references: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-secretsmanager.html
- Amazon Aurora User Guide: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html
- Amazon Aurora pricing (hourly per instance, typically pricier than
  standalone RDS): https://aws.amazon.com/rds/aurora/pricing/

**API-churn note (checked directly against the installed aws-cdk-lib==2.271.0
source in .venv, not recalled from memory):** `DatabaseCluster`/
`DatabaseClusterProps` still accept the older `instances=<int>` and
`instance_props=` combination, but that shape is documented in the CDK
source only for `DatabaseClusterFromSnapshot` back-compat and is superseded
by `writer=`/`readers=`. This stack uses the current, non-deprecated shape:
`writer=rds.ClusterInstance.provisioned("Writer", instance_type=...)`, with
no `readers=` (a single-instance cluster, to keep this module's cost as low
as an Aurora cluster gets - see README.md).

See README.md in this directory for the full explanation, deploy steps, and
- most importantly for this module - the cost warning before deploying to a
real AWS account (Aurora is typically pricier than standalone RDS for an
equivalent instance size).
"""

from __future__ import annotations

from aws_cdk import RemovalPolicy, SecretValue, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from shared.config import AppConfig
from shared.naming import resource_name
from shared.tagging import apply_name_tag, apply_standard_tags

STACK_ID = "RdsAuroraStack"


class RdsAuroraStack(Stack):
    """A small, dedicated 2-AZ VPC plus one Aurora PostgreSQL cluster (one writer, no readers).

    See modules/18_rds_mysql/stack.py for the reasoning behind the 2-AZ VPC
    (Aurora clusters, like standalone RDS instances, need a DB subnet group
    spanning at least two Availability Zones) and the `PRIVATE_ISOLATED`
    subnet placement.

    Unlike modules 18/19 (`rds.DatabaseInstance`, one instance), this module
    uses `rds.DatabaseCluster` - Aurora's storage layer is a separate,
    cluster-level resource shared by one or more compute instances attached
    to it. `writer=` provisions the one required instance; `readers=` is
    left unset, since a read replica is a second billed instance and this
    module's goal is to show the cluster/instance split at the lowest
    possible cost, not to demonstrate read scaling.

    The master password is generated by AWS Secrets Manager (module 09) and
    never appears in this code or in the synthesized template: the secret
    is created first, with a fixed name, and the database receives its
    password as the dynamic reference
    `{{resolve:secretsmanager:<secret-name>:SecretString:password::}}`,
    which CloudFormation resolves at deploy time. It's referenced by *name*
    (a plain string) rather than through `rds.Credentials.from_generated_secret()`
    because that shortcut builds the reference with `Fn::Join` + `Ref`,
    which floci rejects ("Invalid Secrets Manager dynamic reference") - see
    README.md, Notes and cautions.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        config: AppConfig,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        apply_standard_tags(self, tags=config.to_standard_tags())

        vpc_name = resource_name(config.product, config.environment, "vpc", "rds-aurora")
        self.vpc = ec2.Vpc(
            self,
            "Vpc",
            vpc_name=vpc_name,
            ip_addresses=ec2.IpAddresses.cidr("10.22.0.0/16"),
            max_azs=2,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
            ],
        )
        apply_name_tag(self.vpc, vpc_name)

        secret_name = resource_name(config.product, config.environment, "secret", "rds-aurora")
        self.master_secret = secretsmanager.Secret(
            self,
            "MasterSecret",
            secret_name=secret_name,
            description="Master user credentials for the rds-aurora database (generated, never in code).",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template='{"username": "dbadmin"}',
                generate_string_key="password",
                # The same characters CDK's own generated RDS secrets exclude.
                exclude_characters=" %+~`#$&*()|[]{}:;<>?!'/@\"\\",
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )
        apply_name_tag(self.master_secret, secret_name)

        cluster_name = resource_name(config.product, config.environment, "rds", "aurora")
        self.cluster = rds.DatabaseCluster(
            self,
            "Cluster",
            cluster_identifier=cluster_name,
            engine=rds.DatabaseClusterEngine.aurora_postgres(
                version=rds.AuroraPostgresEngineVersion.VER_17_9
            ),
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED),
            credentials=rds.Credentials.from_password(
                "dbadmin",
                # A literal {{resolve:secretsmanager:<name>:...}} string - see the
                # class docstring for why it's by name, not Fn::Join + Ref.
                SecretValue.secrets_manager(secret_name, json_field="password"),
            ),
            writer=rds.ClusterInstance.provisioned(
                "Writer",
                instance_type=ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )
        apply_name_tag(self.cluster, cluster_name)
        # A by-name reference carries no implicit dependency, so make sure the
        # secret exists before CloudFormation creates the database.
        self.cluster.node.add_dependency(self.master_secret)


STACK_CLASS = RdsAuroraStack
