"""Module 18 - RDS for MySQL: a single-AZ managed MySQL database instance.

AWS docs used while writing this module:
- DatabaseInstance construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstance.html
- DatabaseInstanceEngine construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstanceEngine.html
- MysqlEngineVersion construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/MysqlEngineVersion.html
  (checked directly against the installed aws-cdk-lib==2.271.0 source: the
  highest non-deprecated constant is VER_8_4_10 - see README.md for how this
  was verified and why VER_8_0_x constants still exist but are older minor
  versions, not deprecated).
- Credentials construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/Credentials.html
- Secret construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_secretsmanager/Secret.html
- SecretValue.secrets_manager: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/SecretValue.html
- Secrets Manager dynamic references: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-secretsmanager.html
- Amazon RDS - Overview of Amazon RDS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html
- Amazon RDS pricing (hourly billing while the instance exists): https://aws.amazon.com/rds/mysql/pricing/

See README.md in this directory for the full explanation, deploy steps, and
- most importantly for this module - the cost warning before deploying to a
real AWS account.
"""

from __future__ import annotations

from aws_cdk import RemovalPolicy, SecretValue, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from shared.config import AppConfig
from shared.naming import resource_name
from shared.tagging import apply_name_tag, apply_standard_tags

STACK_ID = "RdsMysqlStack"


class RdsMysqlStack(Stack):
    """A small, dedicated VPC plus one db.t3.micro RDS for MySQL instance.

    This module builds its own 2-AZ VPC rather than referencing another
    module's stack (see modules/03_vpc for the full VPC walkthrough). Two
    Availability Zones are used - not one - because Amazon RDS requires a DB
    subnet group to span at least two AZs, even for a single-AZ instance
    deployment (`multi_az` is left at its default of `False` here, so only
    one AZ actually hosts the running instance - the second AZ's subnet only
    satisfies the subnet group requirement).

    The instance is placed in `PRIVATE_ISOLATED` subnets (no route to the
    internet at all, and no NAT Gateway - see modules/03_vpc and
    modules/05_nat_gateway), which is the right default for a database that
    only ever needs to be reached from inside the VPC.

    The master password is generated by AWS Secrets Manager (module 09) and
    never appears in this code or in the synthesized template: the secret
    is created first, with a fixed name, and the database receives its
    password as the dynamic reference
    `{{resolve:secretsmanager:<secret-name>:SecretString:password::}}`,
    which CloudFormation resolves at deploy time. It's referenced by *name*
    (a plain string) rather than through `rds.Credentials.from_generated_secret()`
    because that shortcut builds the reference with `Fn::Join` + `Ref`,
    which floci rejects ("Invalid Secrets Manager dynamic reference") - see
    README.md, Notes and cautions.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        config: AppConfig,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        apply_standard_tags(self, tags=config.to_standard_tags())

        vpc_name = resource_name(config.product, config.environment, "vpc", "rds-mysql")
        self.vpc = ec2.Vpc(
            self,
            "Vpc",
            vpc_name=vpc_name,
            ip_addresses=ec2.IpAddresses.cidr("10.20.0.0/16"),
            max_azs=2,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
            ],
        )
        apply_name_tag(self.vpc, vpc_name)

        secret_name = resource_name(config.product, config.environment, "secret", "rds-mysql")
        self.master_secret = secretsmanager.Secret(
            self,
            "MasterSecret",
            secret_name=secret_name,
            description="Master user credentials for the rds-mysql database (generated, never in code).",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template='{"username": "admin"}',
                generate_string_key="password",
                # The same characters CDK's own generated RDS secrets exclude.
                exclude_characters=" %+~`#$&*()|[]{}:;<>?!'/@\"\\",
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )
        apply_name_tag(self.master_secret, secret_name)

        instance_name = resource_name(config.product, config.environment, "rds", "mysql")
        self.database = rds.DatabaseInstance(
            self,
            "Database",
            instance_identifier=instance_name,
            engine=rds.DatabaseInstanceEngine.mysql(version=rds.MysqlEngineVersion.VER_8_4_10),
            instance_type=ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED),
            credentials=rds.Credentials.from_password(
                "admin",
                # A literal {{resolve:secretsmanager:<name>:...}} string - see the
                # class docstring for why it's by name, not Fn::Join + Ref.
                SecretValue.secrets_manager(secret_name, json_field="password"),
            ),
            allocated_storage=20,
            removal_policy=RemovalPolicy.DESTROY,
            deletion_protection=False,
        )
        apply_name_tag(self.database, instance_name)
        # A by-name reference carries no implicit dependency, so make sure the
        # secret exists before CloudFormation creates the database.
        self.database.node.add_dependency(self.master_secret)


STACK_CLASS = RdsMysqlStack
