"""Module 45 - DocumentDB: a single-instance MongoDB-compatible database cluster.

AWS docs used while writing this module:
- DatabaseCluster construct (L2): https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_docdb/DatabaseCluster.html
  (its properties were also read from the installed aws-cdk-lib==2.271.0
  docstrings: `vpc` "Must be at least 2 subnets in two different AZs",
  `instances` defaults to 1, `storage_encrypted` defaults to true)
- Login construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_docdb/Login.html
- Secret construct: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_secretsmanager/Secret.html
- Secrets Manager dynamic references (`{{resolve:secretsmanager:...}}`): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-secretsmanager.html
- Amazon DocumentDB - Managing instance classes (db.t3.medium supports engine
  versions 3.6.0, 4.0.0, 5.0.0, and 8.0.0): https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html
- What is Amazon DocumentDB: https://docs.aws.amazon.com/documentdb/latest/developerguide/what-is.html
- Amazon DocumentDB pricing (hourly per instance): https://aws.amazon.com/documentdb/pricing/

See README.md in this directory for the full explanation, deploy steps, and
the real-AWS cost warning (a DocumentDB instance bills hourly the moment it
exists, like RDS).
"""

from __future__ import annotations

from aws_cdk import RemovalPolicy, Stack
from aws_cdk import aws_docdb as docdb
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from shared.config import AppConfig
from shared.naming import resource_name
from shared.tagging import apply_name_tag, apply_standard_tags

STACK_ID = "DocumentDbStack"

# Re-check the instance-classes page linked above before changing either
# value: not every instance class supports every engine version.
ENGINE_VERSION = "8.0.0"
INSTANCE_TYPE = "t3.medium"  # CDK adds the "db." prefix -> db.t3.medium
DOCDB_PORT = 27017  # the MongoDB default port, also DocumentDB's default
MASTER_USERNAME = "docdbadmin"


class DocumentDbStack(Stack):
    """A dedicated 2-AZ VPC plus a one-instance DocumentDB cluster.

    Amazon DocumentDB is a managed document database that is compatible with
    the MongoDB API: applications use a regular MongoDB driver and
    connection string. Like Aurora (modules/20_rds_aurora), it separates the
    *cluster* (shared, replicated storage) from its *instances* (the compute
    that serves queries) - here, one instance, the smallest supported class.

    `docdb.DatabaseCluster` is an L2 (curated) construct, unlike the L1-only
    ElastiCache and MSK modules (22 and 46). Two Availability Zones are
    required: the construct's own `vpc` documentation says the subnets must
    span at least two AZs, the same rule RDS has (see modules/18_rds_mysql).

    The master password is generated by AWS Secrets Manager (module 09)
    and never appears in this code or in the synthesized template: the
    cluster receives it as a `{{resolve:secretsmanager:...}}` dynamic
    reference that CloudFormation resolves at deploy time. The secret is
    created explicitly here, instead of letting `docdb.Login(username=...)`
    generate one, because that shortcut also adds a
    `SecretTargetAttachment` which floci can't deploy - see README.md,
    "Notes and cautions".
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        config: AppConfig,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        apply_standard_tags(self, tags=config.to_standard_tags())

        vpc_name = resource_name(config.product, config.environment, "vpc", "docdb")
        self.vpc = ec2.Vpc(
            self,
            "Vpc",
            vpc_name=vpc_name,
            ip_addresses=ec2.IpAddresses.cidr("10.45.0.0/16"),
            max_azs=2,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
            ],
        )
        apply_name_tag(self.vpc, vpc_name)

        sg_name = resource_name(config.product, config.environment, "sg", "docdb")
        self.security_group = ec2.SecurityGroup(
            self,
            "DocDbSecurityGroup",
            vpc=self.vpc,
            security_group_name=sg_name,
            description=f"Allows inbound DocumentDB ({DOCDB_PORT}) from within the VPC only.",
            allow_all_outbound=True,
        )
        self.security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4(self.vpc.vpc_cidr_block),
            connection=ec2.Port.tcp(DOCDB_PORT),
            description="DocumentDB from inside the VPC",
        )
        apply_name_tag(self.security_group, sg_name)

        secret_name = resource_name(config.product, config.environment, "secret", "docdb")
        self.master_secret = secretsmanager.Secret(
            self,
            "MasterSecret",
            secret_name=secret_name,
            description="DocumentDB master user credentials (generated, never in code).",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=f'{{"username": "{MASTER_USERNAME}"}}',
                generate_string_key="password",
                # DocumentDB master passwords can't contain / " @ - the same
                # characters docdb.Login excludes from generated passwords.
                exclude_characters='/"@',
            ),
        )
        apply_name_tag(self.master_secret, secret_name)

        cluster_name = resource_name(config.product, config.environment, "docdb", "main")
        self.cluster = docdb.DatabaseCluster(
            self,
            "Cluster",
            db_cluster_name=cluster_name,
            engine_version=ENGINE_VERSION,
            master_user=docdb.Login(
                username=MASTER_USERNAME,
                password=self.master_secret.secret_value_from_json("password"),
            ),
            instance_type=ec2.InstanceType(INSTANCE_TYPE),
            instances=1,
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED),
            security_group=self.security_group,
            port=DOCDB_PORT,
            storage_encrypted=True,
            # Learning-path choices: let `cdk destroy` remove everything,
            # with no final snapshot - see README.md, Notes and cautions.
            removal_policy=RemovalPolicy.DESTROY,
            deletion_protection=False,
        )
        apply_name_tag(self.cluster, cluster_name)


STACK_CLASS = DocumentDbStack
